# Generated by Django 4.2.2 on 2023-09-03 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_productbrands_options_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_favorited',
            field=models.ManyToManyField(blank=True, related_name='favorite_product', through='products.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
